version: '3'
services:
  jenkins_server:
    image: "registry.jala.info/devops/jenkins/jenkins:2.150.3-alpine"
    ports:
      - "80:8080"
      - "5000:5000"
    volumes:
      - /home/ubuntu/jenkins_home:/var/jenkins_home